Repository AY1920S1-CS2103T-W11-2/main, pull requests merged in 2019-11, with the labels that each got.

#143 Fix Activity list not updating when participants of an Activity changes
  src/main/java/seedu/address/ui/ActivityListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.Medium

#188 UG Fixes
  build.gradle
  docs/UserGuide.adoc
Labels: good first issue, help wanted

#162 Update edit command to only work in view contexts
  docs/UserGuide.adoc
  docs/tutorials/TracingCode.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Title.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditActivityDescriptorBuilder.java
Labels: documentation, priority.High, severity.High, type.Bug, type.Task

#191 Update find command to follow Context
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ActivityCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Context.java
  src/main/java/seedu/address/model/ContextType.java
  src/main/java/seedu/address/model/activity/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/ActivityCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ContextTest.java
  src/test/java/seedu/address/model/activity/TitleContainsKeywordsPredicateTest.java
Labels: priority.High

#185 Delete validation
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/ActivityBook.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: severity.Medium

#193 Add minor cosmetic changes to README and app UI
  README.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/main/resources/view/ActivityHistoryCard.fxml
  src/main/resources/view/ExpenseCard.fxml
Labels: type.Task

#202 Add activity diagram for expense
  docs/DeveloperGuide.adoc
  docs/diagrams/ExpenseActivityDiagram.puml
  docs/images/ExpenseActivityDiagram.png
Labels: documentation

#203 Fix broken UI image in DG and add UI image to DG
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/ListSequenceDiagram.png
Labels: documentation

#205 Add bugfixes and minor features to View command UI
  src/main/java/seedu/address/logic/commands/SettleCommand.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/ui/ActivityCard.java
  src/main/java/seedu/address/ui/ActivityDetailsPanel.java
  src/main/java/seedu/address/ui/ActivityHistoryCard.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/TransferCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/util/UiUtil.java
  src/main/resources/view/ActivityCard.fxml
  src/main/resources/view/ActivityDetailsPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonCard.fxml
  src/test/java/seedu/address/logic/commands/SettleCommandTest.java
  src/test/java/seedu/address/model/activity/ActivityTest.java
Labels: type.Enhancement, type.Task

#206 Improve status bar to show active context; remove debug ID display
  src/main/java/seedu/address/ui/ActivityCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/ActivityCard.fxml
  src/main/resources/view/PersonCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement, type.Task

#211 UG and DG and PPP update
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Edit1.png
  docs/images/Edit2.png
  docs/images/Expense1.png
  docs/images/Expense2.png
  docs/images/NumericalError.png
  docs/images/liakify.jpg
  docs/images/liakify.png
  docs/team/liakify.adoc
Labels: documentation

#209 Add Aulud's PPP; add documentation to UG and DG
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ContextClassDiagram.puml
  docs/diagrams/ContextSwitchActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ContextClassDiagram.png
  docs/images/ContextSwitchActivityDiagram.png
  docs/images/ListComparison.png
  docs/images/ListSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewComparison.png
  docs/team/aulud.adoc
Labels: documentation
