Repository AY1920S1-CS2103T-W11-2/main, pull requests merged in 2019-10, with the labels that each got.

#98 Add ExpenseCommand to add expenses to an Activity after creation
  src/main/java/seedu/address/logic/commands/ActivityCommand.java
  src/main/java/seedu/address/logic/commands/ExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Context.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Expense.java
  src/main/java/seedu/address/model/activity/exceptions/PersonNotInActivityException.java
  src/main/java/seedu/address/model/person/NameContainsAllKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/test/java/seedu/address/logic/commands/ActivityCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ActivityCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExpenseCommandTest.java
  src/test/java/seedu/address/logic/parser/ExpenseCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/activity/ExpenseTest.java
  src/test/java/seedu/address/model/person/NameContainsAllKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/stub/ModelStub.java
  src/test/java/seedu/address/testutil/ActivityBuilder.java
Labels: priority.High

#101 Debt simplification algorithm
  src/main/java/seedu/address/model/activity/Activity.java
  src/test/java/seedu/address/model/activity/ActivityTest.java
  src/test/java/seedu/address/testutil/ActivityBuilder.java
Labels: priority.High

#110 Expense command specifies who is involved
  src/main/java/seedu/address/logic/commands/ExpenseCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseCommandParser.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Expense.java
  src/test/java/seedu/address/logic/commands/ExpenseCommandTest.java
  src/test/java/seedu/address/logic/parser/ExpenseCommandParserTest.java
  src/test/java/seedu/address/model/activity/ActivityTest.java
  src/test/java/seedu/address/testutil/ActivityBuilder.java
Labels: priority.High

#115 Update Model description in DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#116 Add implementation details of List command to DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
Labels: documentation

#106 Update user guide/developer guide for Activity command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ActivityClassDiagram.png
Labels: documentation

#117 Fix InternalState not updating during sample SplitWiser initialisation
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug
